#
#   Makefile S3C Camera driver
#
#   Copyright(c) 2004-2006, Samsung Electronics, Co., Ltd.
#

SENSOR_DIR		= samsung

#
# S3C Camera Interface
#

obj-y			+= s3c_camera.o

s3c_camera-y	+= s3c_camif.o s3c_camera_driver.o

obj-$(CONFIG_VIDEO_SAMSUNG)	+= samsung/